name: Perform Testrun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (Get code from repo)
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set report timestamp
        run: echo "REPORT_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Run Pytest (headless) and create report
        run: |
          pytest --headless \
            --html=tests/reports/report_${REPORT_TIME}.html \
            --self-contained-html -s

      - name: Upload HTML report (as Artifact)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-report
          path: tests/reports/

      - name: Upload logs (as Artifacts)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: tests/logs/

      - name: Upload screenshots (as Artifacts)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: tests/screenshots/
